### ISSUE TITLE
uv not installable on macos

### ISSUE THREAD

**Issue by hardcover-pessimist** [raypappa/ansible-role-dev-server#1]
The parsed url is 

`https://github.com/astral-sh/uv/releases/latest/download/uv-arm64-unknown-darwin.tar.gz`

the correct url is

`https://github.com/astral-sh/uv/releases/download/0.5.31/uv-aarch64-apple-darwin.tar.gz`

relavent facts

```yaml
       "ansible_architecture": "arm64",
        "ansible_os_family": "Darwin",
        "ansible_system": "Darwin",
```
